services:
  app-a:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app
  app-b:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    networks:
      - app
  app-c:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    networks:
      - app
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090"
    networks:
      - app
    depends_on:
      - app-a
networks:
  app:
    driver: bridge
