tempo:
  storage:
    trace:
      backend: gcs
      gcs:
        bucket: grafana-tempo-develop-464014
        service_account_key_path: /var/secrets/gcs/tempo-sa.json

  server:
    log:
      level: debug
      format: logfmt

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

extraVolumes:
  - name: gcs-creds
    secret:
      secretName: tempo-gcs

extraVolumeMounts:
  - name: gcs-creds
    mountPath: /var/secrets/gcs
    readOnly: true
