tempo:
  storage:
    trace:
      backend: gcs
      gcs:
        bucket: grafana-tempo-develop-464014
        service_account: grafana-tempo-gcs@develop-464014.iam.gserviceaccount.com
        insecure: true

  server:
    log:
      level: debug
      format: logfmt

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
