apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-a
data:
  TARGET_API: "http://app-b:8000"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-opentelemetry-collector:4318"
  APP_VERSION: "1.0.0"
  APP_NAME: "app-a"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-b
data:
  TARGET_API: "http://app-c:8000"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-opentelemetry-collector:4318"
  APP_VERSION: "1.0.0"
  APP_NAME: "app-b"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-c
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-opentelemetry-collector:4318"
  APP_VERSION: "1.0.0"
  APP_NAME: "app-c"
---

